### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by dragonauta** [pommi/CGP#115]
Hi, not really an issue.
I added 
```
< meta http-equiv="refresh" content="10" >
```
after head declaration on inc/html.inc.php

This would auto refresh actual page every 10 seconds.
I got this to watch load for all hosts

**Comment by pommi** [comment]
Putting this in your ```conf/config.local.php``` does exactly the same:
```
$CONFIG['page_refresh'] = 10;
```

**Comment by dragonauta** [comment]
Thanks! I didn't find that option into documentation (or maybe I didn't see it)
