### ISSUE TITLE
display of png graphs not working

### ISSUE THREAD

**Issue by christf** [pommi/CGP#116]
The canvas graphs are working well in Firefox but not when using IE.
So I tried the workaround of switching to png. This does not work either.
Apparently there are still canvas graphs being  generated. Graphics in png format are not generated and not visible.

This happens in the current Version from github

I am using IE to display the pages.

**Comment by christf** [comment]
this can be seen on http://sstats.ffm.freifunk.net/sstats (this instance is configured for canvas output) and http://sstats.ffm.freifunk.net/png (this instance is configured for png output)

**Comment by pommi** [comment]
Can you please share what you've configured in which file for PNG?

**Comment by christf** [comment]
On Thursday 26 February 2015 13:02:39 Pim van den Berg wrote:
> Can you please share what you've configured in which file for PNG?
Sure. this is the png-config: I have in config.php:
<?php
$CONFIG['version'] = 5;
$CONFIG['datadir'] = '/var/lib/collectd/rrd';
$CONFIG['typesdb'][] = '/usr/share/collectd/types.db';
$CONFIG['rrdtool'] = '/usr/bin/rrdtool';
$CONFIG['rrdtool_opts'] = array();
$CONFIG['overview'] = array('load', 'cpu', 'memory', 'swap');
$CONFIG['time_range']['default'] = 86400;
$CONFIG['time_range']['uptime']  = 31536000;
$CONFIG['showload'] = true;
$CONFIG['showmem'] = false;
$CONFIG['term'] = array(
	'2hour'	 => 3600 * 2,
	'8hour'	 => 3600 * 8,
	'day'	 => 86400,
	'week'	 => 86400 * 7,
	'month'	 => 86400 * 31,
	'quarter'=> 86400 * 31 * 3,
	'year'	 => 86400 * 365,
);
$CONFIG['network_datasize'] = 'bytes';
$CONFIG['rrd_fetch_method'] = 'sync';
$CONFIG['negative_io'] = false;
$CONFIG['percentile'] = false;
$CONFIG['graph_smooth'] = false;
$CONFIG['graph_minmax'] = false;
$CONFIG['rrd_url'] = 'rrd.php?path={file_escaped}';
$CONFIG['cache'] = 90;
$CONFIG['page_refresh'] = '';
$CONFIG['width'] = 400;
$CONFIG['height'] = 175;
$CONFIG['detail-width'] = 800;
$CONFIG['detail-height'] = 350;
$CONFIG['max-width'] = $CONFIG['detail-width'] * 2;
$CONFIG['max-height'] = $CONFIG['detail-height'] * 2;
$CONFIG['socket'] = NULL;
$CONFIG['flush_type'] = 'collectd';
$CONFIG['default_timezone'] = 'UTC';
if (file_exists(dirname(__FILE__).'/config.local.php'))
	include_once 'config.local.php';



And in config.local.php I have
<?php
$CONFIG['graph_type'] = 'png';
$CONFIG['graph_smooth'] = true;
if (file_exists(dirname(__FILE__).'/config.cat.php'))
	include_once 'config.cat.php';

?>

And in config.cat.php I have:
<?php
$CONFIG['overview'] = array('load', 'cpu', 'memory', 'swap');
#$CONFIG['overview_filter']['ping'] = array('ti' => 'latency', 't' => 
'latency');
#$CONFIG['overview_filter']['interface'] = array('ti' => 'br-client', 't' => 
'if_octets');
#$CONFIG['overview_filter']['interface'] = array('ti' => 'br-client', 't' => 
'if_octets');
$CONFIG['cat']['Freifunk-Server'] = array('uber.ffm.freifunk.net', 
'fastd2.ffm.freifunk.net', 'stats.ffm.freifunk.net', 'fastd3.ffm.freifunk.net', 
'fastd1.ffm.freifunk.net', 'fastdv1.ffm.freifunk.net', 'fastd4.ffm.freifunk.net', 
'fastd5.ffm.freifunk.net', 'fastd6.ffm.freifunk.net', 'fastd7.ffm.freifunk.net', 
'fastd8.ffm.freifunk.net', 'datalxc.ffm.freifunk.net', 'yacy.ffm.freifunk.net');
?>


viele Grüße

Christof

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by pommi** [comment]
I've copied all your configuration to test it, but I just get PNG graphs. I have no idea what why it shows canvas graphs in your case. :confused:

Maybe you should create another directory and just start with a plain git clone of CGP. Don't configure anything. This should by default show PNG graphs.
