### ISSUE TITLE
XSS vulnerability on 'h' parameter in detail.php and host.php

### ISSUE THREAD

**Issue by natrix0-day** [pommi/CGP#118]
Hello,

The 'h' parameter in detail.php and host,php is XSS vulnerable.
It can be validate furthermore by filtering jscript tags.
I've done a very basic patch as follows, but keep in mind that I am not a php programmer, so there could be other errors:
=======================================================

diff -Nurp html-orig/detail.php html/detail.php
--- html-orig/detail.php	2015-05-22 13:18:56.000000000 +0300
+++ html/detail.php	2015-05-22 12:39:51.000000000 +0300
@@ -11,7 +11,7 @@ if (empty($_GET['x']))
 if (empty($_GET['y']))
 	$_GET['y'] = $CONFIG['detail-heigth'];
 
-$host = validate_get(GET('h'), 'host');
+$host = xss_clean( validate_get(GET('h'), 'host') );
 $plugin = validate_get(GET('p'), 'plugin');
 $pinstance = validate_get(GET('pi'), 'pinstance');
 $category = validate_get(GET('c'), 'category');
diff -Nurp html-orig/host.php html/host.php
--- html-orig/host.php	2015-05-22 13:18:37.000000000 +0300
+++ html/host.php	2015-05-22 12:39:01.000000000 +0300
@@ -4,7 +4,7 @@ require_once 'conf/common.inc.php';
 require_once 'inc/html.inc.php';
 require_once 'inc/collectd.inc.php';
 
-$host = validate_get(GET('h'), 'host');
+$host = xss_clean( validate_get(GET('h'), 'host') );
 $plugin = validate_get(GET('p'), 'plugin');
 
 $selected_plugins = !$plugin ? $CONFIG['overview'] : array($plugin);
diff -Nurp html-orig/inc/functions.inc.php html/inc/functions.inc.php
--- html-orig/inc/functions.inc.php	2015-05-22 13:19:13.000000000 +0300
+++ html/inc/functions.inc.php	2015-05-22 11:48:32.000000000 +0300
@@ -8,6 +8,42 @@ function GET($index) {
 	return null;
 }
 
+function xss_clean($data)
+{
+	// Fix &entity\n;
+	$data = str_replace(array('&amp;','&lt;','&gt;'), array('&amp;amp;','&amp;lt;','&amp;gt;'), $data);
+	$data = preg_replace('/(&#*\w+)[\x00-\x20]+;/u', '$1;', $data);
+	$data = preg_replace('/(&#x*[0-9A-F]+);*/iu', '$1;', $data);
+	$data = html_entity_decode($data, ENT_COMPAT, 'UTF-8');
+
+	// Remove any attribute starting with "on" or xmlns
+	$data = preg_replace('#(<[^>]+?[\x00-\x20"\'])(?:on|xmlns)[^>]*+>#iu', '$1>', $data);
+
+	// Remove javascript: and vbscript: protocols
+	$data = preg_replace('#([a-z]*)[\x00-\x20]*=[\x00-\x20]*([`\'"]*)[\x00-\x20]*j[\x00-\x20]*a[\x00-\x20]*v[\x00-\x20]*a[\x00-\x20]*s[\x00-\x20]*c[\x00-\x20]*r[\x00-\x20]*i[\x00-\x20]*p[\x00-\x20]*t[\x00-\x20]*:#iu', '$1=$2nojavascript...', $data);
+	$data = preg_replace('#([a-z]*)[\x00-\x20]*=([\'"]*)[\x00-\x20]*v[\x00-\x20]*b[\x00-\x20]*s[\x00-\x20]*c[\x00-\x20]*r[\x00-\x20]*i[\x00-\x20]*p[\x00-\x20]*t[\x00-\x20]*:#iu', '$1=$2novbscript...', $data);
+	$data = preg_replace('#([a-z]*)[\x00-\x20]*=([\'"]*)[\x00-\x20]*-moz-binding[\x00-\x20]*:#u', '$1=$2nomozbinding...', $data);
+
+	// Only works in IE: <span style="width: expression(alert('Ping!'));"></span>
+	$data = preg_replace('#(<[^>]+?)style[\x00-\x20]*=[\x00-\x20]*[`\'"]*.*?expression[\x00-\x20]*\([^>]*+>#i', '$1>', $data);
+	$data = preg_replace('#(<[^>]+?)style[\x00-\x20]*=[\x00-\x20]*[`\'"]*.*?behaviour[\x00-\x20]*\([^>]*+>#i', '$1>', $data);
+	$data = preg_replace('#(<[^>]+?)style[\x00-\x20]*=[\x00-\x20]*[`\'"]*.*?s[\x00-\x20]*c[\x00-\x20]*r[\x00-\x20]*i[\x00-\x20]*p[\x00-\x20]*t[\x00-\x20]*:*[^>]*+>#iu', '$1>', $data);
+
+	// Remove namespaced elements (we do not need them)
+	$data = preg_replace('#</*\w+:\w[^>]*+>#i', '', $data);
+
+	do
+	{
+		// Remove really unwanted tags
+		$old_data = $data;
+		$data = preg_replace('#</*(?:applet|b(?:ase|gsound|link)|embed|frame(?:set)?|i(?:frame|layer)|l(?:ayer|ink)|meta|object|s(?:cript|tyle)|title|xml)[^>]*+>#i', '', $data);
+	}
+	while ($old_data !== $data);
+
+	// we are done...
+	return $data;
+}
+
 function validate_get($value, $type) {
 	switch($type) {
 		case 'host':
diff -Nurp html-orig/test.php html/test.php
--- html-orig/test.php	1970-01-01 02:00:00.000000000 +0200
+++ html/test.php	2015-05-22 12:29:51.000000000 +0300
@@ -0,0 +1,4 @@
+<?php
+echo "nda";
+?>
+

**Comment by pommi** [comment]
Thanks! :+1: 
Do the last 2 commits fix it for you? https://github.com/pommi/CGP/commits/a213f092ab2a
