### ISSUE TITLE
95th percentil line on the wrong position if 'negative_io' is true

### ISSUE THREAD

**Issue by nazco** [pommi/CGP#119]
If the 'negative_io' option is enabled along with the 'percentile' option in the config the 95 line for transmit is on the wrong site of y axis.
![graph](https://cloud.githubusercontent.com/assets/1292551/7845201/bb999984-04b5-11e5-9fbd-53f9bd350980.png)

**Comment by pommi** [comment]
Thanks :+1: Fixed :smile:
