### ISSUE TITLE
Time to think about a new version ?

### ISSUE THREAD

**Issue by tigerfoot** [pommi/CGP#120]
The last release is really old and a number of commit has been done since.
I believe it would be cool to think to have a release.

**Comment by WillGreen** [comment]
I agree. We're using head, but it would be nice to see a new release version.

**Comment by pommi** [comment]
From the next version, let's call it 1.0, I'll start using rolling releases, where every commit on master is a release.

**Comment by matteocontrini** [comment]
@pommi  when is this 1.0 scheduled for?

**Comment by pommi** [comment]
I tagged v1 :smiley:
