### ISSUE TITLE
Problem with empty sources array in parse_legend

### ISSUE THREAD

**Issue by michaelsalmon** [pommi/CGP#122]
I got the following error when trying to display an aggregated cpu graph:
PHP Warning:  array_combine(): Both parameters should have at least 1 element

I changed line 342 of Base.class.php to:

if (count($sources) > 0) {
        $this->legend = $this->legend + array_combine($sources, $sources);
}

This removed the error message but now I get a JSON response masquerading as a png.

**Comment by pommi** [comment]
I've configured the aggregation, but do not get this warning. Can you share your collectd aggregation plugin configuration, so I can reproduce this?

**Comment by michaelsalmon** [comment]
Here it is:

LoadPlugin aggregation
<Plugin "aggregation">
	<Aggregation>
		Plugin "cpu"
		Type "cpu"

		GroupBy "Host"
		GroupBy "TypeInstance"

		CalculateNum false
		CalculateSum false
		CalculateAverage true
		CalculateMinimum true
		CalculateMaximum true
		CalculateStddev false
	</Aggregation>
</Plugin>

The files generated are:
/var/lib/collectd/eis02/aggregation-cpu-average:
cpu-idle.rrd       cpu-nice.rrd     cpu-steal.rrd   cpu-user.rrd
cpu-interrupt.rrd  cpu-softirq.rrd  cpu-system.rrd  cpu-wait.rrd

/var/lib/collectd/eis02/aggregation-cpu-max:
cpu-idle.rrd       cpu-nice.rrd     cpu-steal.rrd   cpu-user.rrd
cpu-interrupt.rrd  cpu-softirq.rrd  cpu-system.rrd  cpu-wait.rrd

/var/lib/collectd/eis02/aggregation-cpu-min:
cpu-idle.rrd       cpu-nice.rrd     cpu-steal.rrd   cpu-user.rrd
cpu-interrupt.rrd  cpu-softirq.rrd  cpu-system.rrd  cpu-wait.rrd

I tried collectd-web before finding cgp and that can display the aggregated cpu graphs.

**Comment by pommi** [comment]
Thanks! After using your collectd config, I also run into broken images. The commit above fixes it for me. But I'm not sure if we're hitting the same problem, because your workaround in ```Base.class.php``` didn't fix it for me.

**Comment by michaelsalmon** [comment]
I can confirm that it displays the correct graph but I get errors:

PHP Notice:  Undefined variable: aggr in /opt/cgp/graph.php on line 86
