### ISSUE TITLE
rrdcached plugin ?

### ISSUE THREAD

**Issue by gbi39** [pommi/CGP#124]
Hi,

I'm using CGP 0.4.1 under lighttpd on Debian on a box, writing the rrd files collectd produces is handled by rrdcached. This works fine so far, there are also some rrd files with stats of rrdcached, but I can not view them in cgp due to the lack of a rrdcached plugin. 

Clicking on the rrdcached URL produces a 

2015-07-22 13:00:02: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  include(): Failed opening '/var/www/html/cgp/plugin/rrdcached.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/webapps/CGP-0.4.1/inc/collectd.inc.php on line 178

and there is really no rrdcached.php script in /var/www/html/cgp/plugin

So this essentially is a feature request :-)

**Comment by pommi** [comment]
There is no plugin definition for RRDcached in CGP yet. In CGP 0.4.1 it doesn't show you anything. In [more recent versions of CGP](https://github.com/pommi/CGP/archive/master.zip) it tries to create the graphs automatically. The graphs can be improved by defining the ```plugin/rrdcached.json``` file. If you have created a ```rrdcached.json``` file you're happy with, please share it and it can be included in CGP.
