### ISSUE TITLE
"Invalid type instance" warnings

### ISSUE THREAD

**Issue by rfnx** [pommi/CGP#132]
Hello,

I have a small issue with CGP for months, but I can't remember when it started (I keep CGP updated with the git repo).
Everytime I load a page (index or any other stats page like "uptime") I have warnings in my php logs : 

```
Invalid plugin instance in $_GET["pi"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid plugin instance in $_GET["pi"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid plugin instance in $_GET["pi"]: ""
Invalid type instance in $_GET["ti"]: ""
Invalid plugin instance in $_GET["pi"]: ""
Invalid type instance in $_GET["ti"]: ""
PHP Notice:  Undefined variable: html_weburl in /srv/http/collectdgp/inc/html.inc.php on line 131
```

I'm currently using collectd with these plugins : cpu, df, disk, entropy, interface, load, memory, nginx, rrdcached, uptime.
I checked my CGP config multiple times and it seems fine so I really don't know what to do. But it's not critical since the website seems to work fine.

Thanks for CGP ! Bye.

**Comment by SinafdeGiraf** [comment]
I have the same error messages, but I only get four (2x "plugin instance", 2x "type instance") and the PHP Notice.

I also got an`PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/cgp/inc/collectd.inc.php on line 142`. I "fixed" that one by putting a `if (is_array($plugindata) || is_object($plugindata)){}` around the `foreach ($plugindata as $item)` segment:

	if (is_array($plugindata) || is_object($plugindata))
	{
	# type instances should be grouped in 1 graph
		foreach ($plugindata as $item) {
			# backwards compatibility
			if ($CONFIG['version'] >= 5 || !preg_match('/^(df|interface)$/', $item['p']))
				if (!(
					$item['p'] == 'libvirt'
					|| ($item['p'] == 'snmp' && $item['t'] == 'if_octets')
					|| ($item['p'] == 'vmem' && $item['t'] == 'vmpage_io')
				))
					unset($item['ti']);
			$data[] = $item;
		}
	}

I don't know anything about PHP, though. I just searched for the error and followed advice on stackoverflow.

**Comment by rsheep** [comment]
to get rid of:
```
PHP Notice:  Undefined variable: html_weburl in /srv/http/collectdgp/inc/html.inc.php on line 131
```

you can add 
```
$html_weburl = htmlentities($CONFIG['weburl']);
```
just before.


That line should be probably moved at the start of htm_end() function.

Still investigating the Invalid plugin/type instance error.

**Comment by SinafdeGiraf** [comment]
Thank you. I've put it in the head section of the function you mentioned and the error is gone.

I would like to help more regarding the other error, but, again, my programming skills are mostly limited to googling and copy&pasting things together.

**Comment by pommi** [comment]
Thanks for reporting! The warnings should be gone now.
