### ISSUE TITLE
How to disable the display of certain data sources with the new JSON graphing method?

### ISSUE THREAD

**Issue by bpkroth** [pommi/CGP#133]
For instance, graphing of "Open Slots" in the Apache Scoreboard graph when they're very high compared with the other values can make reading the stacked graph very difficult.  In the past, I was able to just comment out the line defining the "open" data source to prevent it from being displayed, but that doesn't seem to work with the JSON method.  Thoughts?

Thanks,
Brian

**Comment by pommi** [comment]
Hi Brian,

This is quite hard right now, because graphs are generated automatically based on the available data. The JSON is just an addition to make the graphs prettier. Currently you should dig around in all ```type/xxx.class.php``` files to exclude some sources, but that's quite hard.
