### ISSUE TITLE
I want to see the dynamic changes without refreshing the browser. How to set ?

### ISSUE THREAD

**Issue by baiwfg2** [pommi/CGP#139]

**Comment by Lekensteyn** [comment]
Set `$CONFIG['page_refresh'] = '30';` in conf/config.php to make it update every 30secs.

**Comment by baiwfg2** [comment]
I found one issue. I set page_refresh relatively low, for example, 2 seconds. Every time the page is refreshed, the graphs which  were zoomed in by myself return to the original look, which doesn't look well. I want refreshment not to influence the zoomed graphs.

**Comment by pommi** [comment]
This is currently not possible. Some kind of javascript / AJAX interaction should be implemented for this, so it will only update the graphs and not refresh the whole page.

Feel free to develop this feature and send in a Pull Request.
