### ISSUE TITLE
rrd-files are not compressed

### ISSUE THREAD

**Issue by Arvur** [pommi/CGP#155]
Hello!

Linux Mint 18.3 + Apache/2.4.18 (Ubuntu) + PHP 7.0.
Ajax responses from rrd.php do not get compressed. 
Everything else has "Content-Encoding: gzip"  (mod_deflate is enabled by default).
Seems SetOutputFilter in .htaccess makes no effect but I do not see the reason.

**Comment by BubonicPestilence** [comment]
Probably something wrong with your configuration.
Works perfectly on nginx + fpm7.0

**Comment by Arvur** [comment]
This is clean install with default configuration. Reproduced on two PC-s.
Configuration problems seem the right reason but I cannot see how to fix it.

**Comment by BubonicPestilence** [comment]
Can you share .htaccess and vhost configuration?

**Comment by Arvur** [comment]
Here they are. Both are default though.
[htaccess+vhosts.zip](https://github.com/pommi/CGP/files/1635261/htaccess.vhosts.zip)

**Comment by BubonicPestilence** [comment]
`$CONFIG['rrd_url']` what value you have in conf/config.php ?

Also share config.php :D

**Comment by BubonicPestilence** [comment]
And `httpd -M` output :)

**Comment by Arvur** [comment]
arvur@F3JP ~ $ httpd -M
httpd: command not found

arvur@F3JP ~ $ apachectl -M
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 setenvif_module (shared)
 status_module (shared)

[config.local.php.zip](https://github.com/pommi/CGP/files/1635314/config.local.php.zip)

**Comment by Arvur** [comment]
config.php is unchanged:
$CONFIG['rrd_url'] = 'rrd.php?path={file_escaped}';

**Comment by BubonicPestilence** [comment]
Let's simply `.htaccess`, check output headers for requests after applying this.

```
Options -Indexes

<IfModule mod_deflate.c>
    Header set x-bp-deflate works
    
    <FilesMatch "rrd.php\$">
        Header set x-bp-filesmatch works
        
        SetOutputFilter DEFLATE
    </Files>
</IfModule>

RewriteEngine On
RewriteRule ^.git(ignore|/) - [F,L]
```

**Comment by Arvur** [comment]
I've added this to vhosts
```
<Directory / >
    AllowOverride All
</Directory>
```
and your .htaccess modification. No new fields in response ((

**Comment by BubonicPestilence** [comment]
skype: fg_registrar

**Comment by Arvur** [comment]
Ah! Got it to work. Correct vhost modification:
```
<Directory "/var/www/html" >
    AllowOverride All
</Directory>
```
And fix for mod_rewrite:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^.git(ignore|/) - [F,L]
</IfModule>
```

**Comment by BubonicPestilence** [comment]
What baout headers?

**Comment by Arvur** [comment]
Invalid command 'Header' in error.log

**Comment by BubonicPestilence** [comment]
Can you enable/install `mod_headers`, it will be simplier to debug :)

**Comment by Arvur** [comment]
No need to debug, pull requests #156 and #157 fixed my problem.

**BubonicPestilence**, thanks a lot for your support!
