### ISSUE TITLE
PHP 7.2 -> 7.3 breaks CGP

### ISSUE THREAD

**Issue by bjornfor** [pommi/CGP#171]
I recently upgraded from NixOS 19.03 to 19.09 and collectd-graph-panel started showing "Unknown host" for any host I try to view metrics from. Going back to PHP 7.2  (NixOS 19.09 defaults to PHP 7.3) fixes the issue.

I did some manual tracing and it seems the GET function in CGP behaves differently between the two PHP versions.

**Comment by schnitzi99** [comment]
I had the same issue with a debian based upgrade to php7.3.
After cloning the current master (not downloading the release) the problem just went away.

**Comment by pommi** [comment]
This seems to be fixed in commit 16e710fe4e462ef80302014ab4ac6628d412c664

**Comment by bjornfor** [comment]
Any plans to make a new release?

**Comment by bjornfor** [comment]
> Any plans to make a new release?

Friendly ping.

(php 7.2 is removed from nixos-20.09, so now I have to start fetching master branch, which I feel is conceptually wrong for end-users to do.)

**Comment by neingeist** [comment]
I also encountered this issue, a new release would be nice!
