### ISSUE TITLE
redis plugin

### ISSUE THREAD

**Issue by jbergstroem** [pommi/CGP#56]
Lets get it in. I'll do a pull req as soon as https://github.com/collectd/collectd/pull/464 is in a collectd release since that's when I will start using this. Just thought I'd do an issue in case someone else wants to add the lines needed.

**Comment by kiranos** [comment]
@jbergstroem did you create a plugin for redis?:)

**Comment by pricejn2** [comment]
It looks like this issue has been closed for quite a while, but I'm not seeing where this made it into CGP. Am I missing something?

**Comment by pommi** [comment]
I never received a pull request.

**Comment by jbergstroem** [comment]
Sorry, I've since moved away from CGP.

**Comment by reswild** [comment]
This project seems pretty dead, but if anyone still needs a Redis plugin, I've started making one at https://github.com/reswild/cgp-redis
